### ISSUE TITLE
rake db:fixtures in readme.md is out of date

### ISSUE THREAD

**Issue by paplm** [rubyclerks/sales_clerk#12]
just try to follow your instruction and found that `rake db:fixtures` in Get running session in readme.md is not working anymore
it should be `rake db:load_fixtures_en[fr]` is not it?

great code BTW, Cheer :)

**Comment by dancinglightning** [comment]
Hi, and thanks. The rails girls did the change and i didn't see that (off course i don't use it either)

rake -T spits out   rake db:load_fixtures_en

i don't know about the [fr] , i think we only have en or fi 

I would be happy to accept a pull request if you get it working for you.
