### ISSUE TITLE
Can't edit categories

### ISSUE THREAD

**Issue by marcfuentes** [rubyclerks/sales_clerk#2]
Hi, wonderful app, but I got a problem, when I want to edit a product category in development it never updates, console looks like this

![image](https://cloud.githubusercontent.com/assets/2789067/6557888/56e41470-c657-11e4-95b9-f53ea7d9b721.png)

thanks in advance.

**Comment by dancinglightning** [comment]
Hi,
so you cloned the salesclerk and migrated, right?
and you have an admin user and can create users and products?
What ruby version ?
and can you try in the console?

**Comment by marcfuentes** [comment]
Yes, I clones salesclerk, migrated, have a admin user, can create users and products, categories, my version of ruby is 1.9.3p551, maybe is too old for your system?

**Comment by dancinglightning** [comment]
sorry i was travelling, am no loner in asia :-(

1.9.3 should be fine. I will try this on my machine in the next days

**Comment by drhenner** [comment]
@marcfuentes even if 1.9.3 works, why would you use it on a new/newish app?  1.9.3 is no longer supported.  (I hope that helps your decision on upgrade to 2.0 or 2.1 or 2.2)

@dancinglightning hope you enjoyed your trip.  Did I tell you I went to Ukraine for a ruby conf?  Crazy the plain went down a week or 2 later.

**Comment by dancinglightning** [comment]
ok, i tried. but it works for me, with 1.9.3
both creating and editing. 
is your category online, and what are you trying to edit exactly?
so you would need to be more precise about the steps you made and errors, otherwise i can't help

**Comment by marcfuentes** [comment]
@drhenner you're right, I should update the ruby version, the thing is all my current projects are using 1.9.3 and I was trying to avoid deal with RVM.

@dancinglightning yes, I put the category online, And I've tried to edit the category after this was created and then it enters in this kind of endless loop, I'm going to clone the app again and see what happens, thanks for your time!

**Comment by dancinglightning** [comment]
@marcfuentes I would like to close this unless you have some more information
