### ISSUE TITLE
default english data & rake task

### ISSUE THREAD

**Issue by aberracja** [rubyclerks/sales_clerk#3]
we need default data (product categories, products in each category). We can use rake or fixtures.

**Comment by dancinglightning** [comment]
Yes.either

-------- Original message --------

**Comment by dancinglightning** [comment]
Actually i just remembered: the project uses the gem db_fixtures_dump
I don't remember the syntax, try rake -T
It dumps the whole db as yaml that can then be read as fixtures. So all you have to do is click click , give good names, fill all the data, and then dump and you have the data.

**Comment by Czarrrna** [comment]
Ok, thanks.
cc / @pjar

**Comment by Czarrrna** [comment]
@dancinglightning : Ok, we manage to load the database from fixtures, but we couldn't be able to dump our own data to fixtures and we are not sure if you want us to make some default data in English or it is just for our practice?

**Comment by dancinglightning** [comment]
yes, english please.
off course you can try to make it dependent on the locale too, but 
polish is to most what finish is to you.

**Comment by aberracja** [comment]
Now we need new rake task to load english fixtures

**Comment by Czarrrna** [comment]
Done.

**Comment by dancinglightning** [comment]
ok, well done
